### ISSUE TITLE
Retirar archivo secrets.json que se encuentra dentro de la carpeta 'reserva_espacios'.

### ISSUE THREAD

**Issue by JhonFrederick** [JhonFrederick/entrenamiento-cedesoft-2019#3]
El archivo secrets.json al que me estoy refiriendo es el que esta ubicado en la siguiente ruta: **.../reserva_espacios/reserva_espacios/secrets.json**

No deberia estar ubicado ahí para evitar que se le realice seguimiento a ese archivo y genere ruido

**Comment by ldavidrh** [comment]
Listo, ya puse el archivo secrets.json en la ubicacion correcta
